config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    devise_for :users, path: '/', controllers: {
      sessions: 'public/users/sessions',
      registrations: 'public/users/registrations'
    }
    root 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    resources :homes, only: [:edit, :update, :destroy]
    delete 'projects/:id/image' => 'projects#image_destroy', as: 'image_destroy'
    resources :projects, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :tasks, only: [:show, :create, :edit, :update, :destroy ]
      delete 'tasks/:id/image' => 'tasks#task_image_destroy', as: 'task_image_destroy'
    end
    resource :task_relationships, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_one_attached :project_image
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  belongs_to :project
  has_one_attached :task_image

  enum progress: { incomplete: 0, to_do: 1, complete: 2, standby: 3 }
  validates :title, presence: true, length: { maximum: 50 }
  
  has_many :child_relationships, dependent: :destroy, class_name: "TaskRelationship", foreign_key: "parent_task_id"
  has_many :parent_relationships, dependent: :destroy, class_name: "TaskRelationship", foreign_key: "child_task_id"
  has_many :child_tasks, through: :child_relationships, source: :child_task
  has_many :parent_tasks, through: :parent_relationships, source: :parent_task
end

app/models/task_relationship.rb
class TaskRelationship < ApplicationRecord
  belongs_to :parent_task, class_name: "Task"
  belongs_to :child_task, class_name: "Task"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :validatable, :rememberable
         #:recoverable,
  has_many :projects, dependent: :destroy
  has_many :tasks, dependent: :destroy
  has_one_attached :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <ul class="alert alert-warning">
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash_message.html.erb
<% if notice %>
  <div class="alert alert-success">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_global_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <li class="navbar-brand">
      <%= link_to 'Passion Suchedule', root_path %>
    </li>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'about', about_path, class: "nav-link" %>
        </li>

        <% if current_user %>
          <li class="nav-item">
            <%= link_to 'new project', new_project_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'logout', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'login', new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'signup', new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Passion Shedule</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/223bfd9c1c.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/global_navigation" %>
    </header>
    <div class="container">
      <%= render "layouts/flash_message" %>
      <%= yield %>
    </div>
    <%= debug params if Rails.env.development? %>
  </body>
</html>